"""Translation catalogs for user-facing text generated by the backend (emails, alerts).

Catalogs are flat JSON files (`locales/<language>.json`) mapping keys to `str.format`
templates. Lookups fall back to English, then to the key itself, so a missing translation
never breaks a notification.
"""

import json
from collections.abc import Iterator
from contextlib import contextmanager
from contextvars import ContextVar
from enum import StrEnum
from functools import cache
from pathlib import Path
from typing import Any

_LOCALES_DIR = Path(__file__).parent / "locales"


class Language(StrEnum):
    EN = "en"
    FR = "fr"
    AR = "ar"


DEFAULT_LANGUAGE = Language.EN

# Language of the current request (the authenticated user's preference) or job iteration.
_current_language: ContextVar[Language] = ContextVar("language", default=DEFAULT_LANGUAGE)


def get_current_language() -> Language:
    return _current_language.get()


def set_current_language(language: Language | str | None) -> None:
    _current_language.set(resolve_language(language))


@contextmanager
def use_language(language: Language | str | None) -> Iterator[None]:
    token = _current_language.set(resolve_language(language))
    try:
        yield
    finally:
        _current_language.reset(token)


class _KeepMissing(dict[str, Any]):
    """format_map helper leaving unknown placeholders untouched instead of raising."""

    def __missing__(self, key: str) -> str:
        return "{" + key + "}"


@cache
def load_catalog(language: Language) -> dict[str, str]:
    path = _LOCALES_DIR / f"{language.value}.json"
    catalog: dict[str, str] = json.loads(path.read_text(encoding="utf-8"))
    return catalog


def resolve_language(value: Language | str | None) -> Language:
    try:
        return Language(value) if value else DEFAULT_LANGUAGE
    except ValueError:
        return DEFAULT_LANGUAGE


def has_translation(key: str, language: str | Language | None = None) -> bool:
    return key in load_catalog(resolve_language(language)) or key in load_catalog(DEFAULT_LANGUAGE)


def translate(key: str, language: str | Language | None = None, **params: Any) -> str:
    """Render `key`; without an explicit language, the current context language is used."""
    lang = resolve_language(language) if language else get_current_language()
    template = load_catalog(lang).get(key) or load_catalog(DEFAULT_LANGUAGE).get(key) or key
    return template.format_map(_KeepMissing(params))
