"""Translation catalogs for user-facing text generated by the backend (emails, alerts).

Catalogs are flat JSON files (`locales/<language>.json`) mapping keys to `str.format`
templates. Lookups fall back to English, then to the key itself, so a missing translation
never breaks a notification.
"""

import json
from enum import StrEnum
from functools import cache
from pathlib import Path
from typing import Any

_LOCALES_DIR = Path(__file__).parent / "locales"


class Language(StrEnum):
    EN = "en"
    FR = "fr"
    AR = "ar"


DEFAULT_LANGUAGE = Language.EN


class _KeepMissing(dict[str, Any]):
    """format_map helper leaving unknown placeholders untouched instead of raising."""

    def __missing__(self, key: str) -> str:
        return "{" + key + "}"


@cache
def load_catalog(language: Language) -> dict[str, str]:
    path = _LOCALES_DIR / f"{language.value}.json"
    catalog: dict[str, str] = json.loads(path.read_text(encoding="utf-8"))
    return catalog


def resolve_language(value: str | None) -> Language:
    try:
        return Language(value) if value else DEFAULT_LANGUAGE
    except ValueError:
        return DEFAULT_LANGUAGE


def has_translation(key: str, language: str | Language | None = None) -> bool:
    return key in load_catalog(resolve_language(language)) or key in load_catalog(DEFAULT_LANGUAGE)


def translate(key: str, language: str | Language | None = None, **params: Any) -> str:
    lang = resolve_language(language)
    template = load_catalog(lang).get(key) or load_catalog(DEFAULT_LANGUAGE).get(key) or key
    return template.format_map(_KeepMissing(params))
