"""File storage backends.

Files are addressed by opaque keys generated by the server (never by user input). The local
backend writes under UPLOAD_DIRECTORY; an S3-compatible backend can implement the same
protocol, and `attachments.storage_backend` records where each file lives.
"""

import os
import tempfile
from collections.abc import AsyncIterator
from datetime import UTC, datetime
from pathlib import Path
from typing import Protocol

import anyio

from app.core.config import Settings

CHUNK_SIZE = 64 * 1024


class StorageBackend(Protocol):
    name: str

    async def save(self, key: str, content: bytes) -> None: ...

    def open(self, key: str) -> AsyncIterator[bytes]: ...

    async def delete(self, key: str) -> None: ...

    async def exists(self, key: str) -> bool: ...

    def list_keys(self, older_than: datetime) -> AsyncIterator[str]: ...


class StorageKeyError(ValueError):
    """Raised when a key would escape the storage root."""


class LocalStorageBackend:
    name = "local"

    def __init__(self, root: Path) -> None:
        self.root = root.resolve()

    def _path(self, key: str) -> Path:
        path = (self.root / key).resolve()
        if not path.is_relative_to(self.root) or path == self.root:
            raise StorageKeyError(f"Invalid storage key: {key!r}")
        return path

    async def save(self, key: str, content: bytes) -> None:
        path = self._path(key)

        def write() -> None:
            path.parent.mkdir(parents=True, exist_ok=True)
            # Write to a temporary file, then rename: readers never see partial files.
            descriptor, temporary = tempfile.mkstemp(dir=path.parent, prefix=".upload-")
            try:
                with os.fdopen(descriptor, "wb") as handle:
                    handle.write(content)
                os.replace(temporary, path)
            except BaseException:
                Path(temporary).unlink(missing_ok=True)
                raise

        await anyio.to_thread.run_sync(write)

    async def open(self, key: str) -> AsyncIterator[bytes]:
        async with await anyio.open_file(self._path(key), "rb") as handle:
            while chunk := await handle.read(CHUNK_SIZE):
                yield chunk

    async def delete(self, key: str) -> None:
        await anyio.to_thread.run_sync(lambda: self._path(key).unlink(missing_ok=True))

    async def exists(self, key: str) -> bool:
        return await anyio.Path(self._path(key)).is_file()

    async def list_keys(self, older_than: datetime) -> AsyncIterator[str]:
        """Stored keys last modified before `older_than` (temporary files excluded)."""
        cutoff = older_than.timestamp()
        paths = await anyio.to_thread.run_sync(lambda: list(self.root.rglob("*")))
        for path in paths:
            if path.is_file() and not path.name.startswith(".") and path.stat().st_mtime < cutoff:
                yield path.relative_to(self.root).as_posix()


def build_storage(settings: Settings) -> StorageBackend:
    settings.upload_directory.mkdir(parents=True, exist_ok=True)
    return LocalStorageBackend(settings.upload_directory)


def utc_now() -> datetime:
    return datetime.now(UTC)
