"""create reminders

Revision ID: 92d6f7b963c0
Revises: cbdee638d635
Create Date: 2026-10-07 11:23:57.172751+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "92d6f7b963c0"
down_revision: str | None = "cbdee638d635"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reminders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("due_mileage", sa.Integer(), nullable=True),
        sa.Column("warning_before_days", sa.Integer(), server_default="7", nullable=False),
        sa.Column("warning_before_km", sa.Integer(), server_default="500", nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "due_date IS NOT NULL OR due_mileage IS NOT NULL", name=op.f("ck_reminders_has_due")
        ),
        sa.CheckConstraint("due_mileage >= 0", name=op.f("ck_reminders_due_mileage_positive")),
        sa.CheckConstraint(
            "warning_before_days >= 0", name=op.f("ck_reminders_warning_before_days_positive")
        ),
        sa.CheckConstraint(
            "warning_before_km >= 0", name=op.f("ck_reminders_warning_before_km_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_reminders_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_reminders_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminders")),
    )
    op.create_index(op.f("ix_reminders_vehicle_id"), "reminders", ["vehicle_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reminders_vehicle_id"), table_name="reminders")
    op.drop_table("reminders")
    # ### end Alembic commands ###
