"""create vehicles and vehicle access

Revision ID: 3cd0f848c45f
Revises: 20f2e0d71b4e
Create Date: 2026-10-06 14:53:54.595051+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "3cd0f848c45f"
down_revision: str | None = "20f2e0d71b4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("nickname", sa.String(length=100), nullable=True),
        sa.Column("brand", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("trim", sa.String(length=64), nullable=True),
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.Column("license_plate", sa.String(length=20), nullable=True),
        sa.Column("vin", sa.String(length=32), nullable=True),
        sa.Column("fuel_type", sa.String(length=20), nullable=False),
        sa.Column("transmission_type", sa.String(length=20), nullable=True),
        sa.Column("engine", sa.String(length=64), nullable=True),
        sa.Column("engine_displacement_cc", sa.Integer(), nullable=True),
        sa.Column("horsepower", sa.SmallInteger(), nullable=True),
        sa.Column("color", sa.String(length=32), nullable=True),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("purchase_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("initial_mileage", sa.Integer(), server_default="0", nullable=False),
        sa.Column("current_mileage", sa.Integer(), server_default="0", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fuel_type IN ('petrol', 'diesel', 'electric', 'hybrid', 'plug_in_hybrid', 'lpg', 'cng', 'hydrogen', 'other')",
            name=op.f("ck_vehicles_fuel_type"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'sold', 'archived')", name=op.f("ck_vehicles_status")
        ),
        sa.CheckConstraint(
            "transmission_type IN ('manual', 'automatic', 'semi_automatic', 'cvt', 'dual_clutch', 'other')",
            name=op.f("ck_vehicles_transmission_type"),
        ),
        sa.CheckConstraint(
            "current_mileage >= 0", name=op.f("ck_vehicles_current_mileage_positive")
        ),
        sa.CheckConstraint(
            "engine_displacement_cc > 0", name=op.f("ck_vehicles_displacement_positive")
        ),
        sa.CheckConstraint("horsepower > 0", name=op.f("ck_vehicles_horsepower_positive")),
        sa.CheckConstraint(
            "initial_mileage >= 0", name=op.f("ck_vehicles_initial_mileage_positive")
        ),
        sa.CheckConstraint("purchase_price >= 0", name=op.f("ck_vehicles_purchase_price_positive")),
        sa.CheckConstraint("year BETWEEN 1886 AND 2100", name=op.f("ck_vehicles_year_range")),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_vehicles_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
    )
    op.create_index(op.f("ix_vehicles_license_plate"), "vehicles", ["license_plate"], unique=False)
    op.create_index(op.f("ix_vehicles_owner_id"), "vehicles", ["owner_id"], unique=False)
    op.create_index(
        "uq_vehicles_owner_id_vin",
        "vehicles",
        ["owner_id", "vin"],
        unique=True,
        postgresql_where=sa.text("vin IS NOT NULL"),
    )
    op.create_table(
        "vehicle_access",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("granted_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('editor', 'viewer')", name=op.f("ck_vehicle_access_role")),
        sa.ForeignKeyConstraint(
            ["granted_by_id"],
            ["users.id"],
            name=op.f("fk_vehicle_access_granted_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_vehicle_access_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_vehicle_access_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle_access")),
        sa.UniqueConstraint(
            "vehicle_id", "user_id", name=op.f("uq_vehicle_access_vehicle_id_user_id")
        ),
    )
    op.create_index(op.f("ix_vehicle_access_user_id"), "vehicle_access", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vehicle_access_user_id"), table_name="vehicle_access")
    op.drop_table("vehicle_access")
    op.drop_index(
        "uq_vehicles_owner_id_vin",
        table_name="vehicles",
        postgresql_where=sa.text("vin IS NOT NULL"),
    )
    op.drop_index(op.f("ix_vehicles_owner_id"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_license_plate"), table_name="vehicles")
    op.drop_table("vehicles")
    # ### end Alembic commands ###
