"""create oil changes

Revision ID: 7d5df43bcd7d
Revises: 4ae57620391f
Create Date: 2026-10-06 15:42:28.501384+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "7d5df43bcd7d"
down_revision: str | None = "4ae57620391f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oil_changes",
        sa.Column("maintenance_record_id", sa.Uuid(), nullable=False),
        sa.Column("oil_brand", sa.String(length=80), nullable=True),
        sa.Column("oil_type", sa.String(length=20), nullable=True),
        sa.Column("oil_viscosity", sa.String(length=20), nullable=True),
        sa.Column("oil_quantity_liters", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "oil_filter_changed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("filter_brand", sa.String(length=80), nullable=True),
        sa.Column("filter_reference", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "oil_type IN ('synthetic', 'semi_synthetic', 'mineral', 'high_mileage', 'other')",
            name=op.f("ck_oil_changes_oil_type"),
        ),
        sa.CheckConstraint(
            "oil_quantity_liters > 0", name=op.f("ck_oil_changes_oil_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["maintenance_record_id"],
            ["maintenance_records.id"],
            name=op.f("fk_oil_changes_maintenance_record_id_maintenance_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("maintenance_record_id", name=op.f("pk_oil_changes")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oil_changes")
    # ### end Alembic commands ###
