"""create maintenance schedules

Revision ID: cc5c160f6ff0
Revises: 54b2193165cf
Create Date: 2026-10-06 15:08:34.903941+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "cc5c160f6ff0"
down_revision: str | None = "54b2193165cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maintenance_schedules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("maintenance_type_id", sa.Uuid(), nullable=False),
        sa.Column("interval_km", sa.Integer(), nullable=True),
        sa.Column("interval_months", sa.SmallInteger(), nullable=True),
        sa.Column("last_service_date", sa.Date(), nullable=True),
        sa.Column("last_service_mileage", sa.Integer(), nullable=True),
        sa.Column("next_service_date", sa.Date(), nullable=True),
        sa.Column("next_service_mileage", sa.Integer(), nullable=True),
        sa.Column("warning_before_km", sa.Integer(), server_default="1000", nullable=False),
        sa.Column("warning_before_days", sa.Integer(), server_default="30", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "interval_km > 0", name=op.f("ck_maintenance_schedules_interval_km_positive")
        ),
        sa.CheckConstraint(
            "interval_km IS NOT NULL OR interval_months IS NOT NULL",
            name=op.f("ck_maintenance_schedules_has_interval"),
        ),
        sa.CheckConstraint(
            "interval_months > 0", name=op.f("ck_maintenance_schedules_interval_months_positive")
        ),
        sa.CheckConstraint(
            "last_service_mileage >= 0",
            name=op.f("ck_maintenance_schedules_last_service_mileage_positive"),
        ),
        sa.CheckConstraint(
            "warning_before_days >= 0",
            name=op.f("ck_maintenance_schedules_warning_before_days_positive"),
        ),
        sa.CheckConstraint(
            "warning_before_km >= 0",
            name=op.f("ck_maintenance_schedules_warning_before_km_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["maintenance_type_id"],
            ["maintenance_types.id"],
            name=op.f("fk_maintenance_schedules_maintenance_type_id_maintenance_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_maintenance_schedules_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_schedules")),
        sa.UniqueConstraint(
            "vehicle_id",
            "maintenance_type_id",
            name=op.f("uq_maintenance_schedules_vehicle_id_maintenance_type_id"),
        ),
    )
    op.create_index(
        op.f("ix_maintenance_schedules_maintenance_type_id"),
        "maintenance_schedules",
        ["maintenance_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maintenance_schedules_next_service_date"),
        "maintenance_schedules",
        ["next_service_date"],
        unique=False,
        postgresql_where=sa.text("enabled"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_maintenance_schedules_next_service_date"),
        table_name="maintenance_schedules",
        postgresql_where=sa.text("enabled"),
    )
    op.drop_index(
        op.f("ix_maintenance_schedules_maintenance_type_id"), table_name="maintenance_schedules"
    )
    op.drop_table("maintenance_schedules")
    # ### end Alembic commands ###
