"""create alerts

Revision ID: a87cf4ec144e
Revises: 509870d617ee
Create Date: 2026-10-06 15:19:30.800069+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a87cf4ec144e"
down_revision: str | None = "509870d617ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=True),
        sa.Column("alert_type", sa.String(length=30), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("dedup_key", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("template_key", sa.String(length=100), nullable=True),
        sa.Column(
            "template_params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=10), server_default="active", nullable=False),
        sa.Column("trigger_date", sa.Date(), nullable=True),
        sa.Column("trigger_mileage", sa.Integer(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "alert_type IN ('maintenance_due', 'document_expiration', 'insurance_expiration', 'inspection_due', 'part_lifetime', 'mileage_reminder', 'custom_reminder', 'system')",
            name=op.f("ck_alerts_alert_type"),
        ),
        sa.CheckConstraint(
            "priority IN ('info', 'low', 'medium', 'high', 'critical')",
            name=op.f("ck_alerts_priority"),
        ),
        sa.CheckConstraint(
            "source_type IN ('maintenance_schedule', 'vehicle_document', 'part_replacement', 'vehicle', 'reminder')",
            name=op.f("ck_alerts_source_type"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'read', 'dismissed', 'resolved')", name=op.f("ck_alerts_status")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_alerts_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_alerts_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
        sa.UniqueConstraint("user_id", "dedup_key", name=op.f("uq_alerts_user_id_dedup_key")),
    )
    op.create_index(
        op.f("ix_alerts_source_type_source_id"),
        "alerts",
        ["source_type", "source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alerts_user_id_status_created_at"),
        "alerts",
        ["user_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alerts_vehicle_id_status"), "alerts", ["vehicle_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alerts_vehicle_id_status"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_user_id_status_created_at"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_source_type_source_id"), table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
