"""create maintenance records

Revision ID: 54b2193165cf
Revises: fa5060fec212
Create Date: 2026-10-06 15:04:52.993688+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "54b2193165cf"
down_revision: str | None = "fa5060fec212"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maintenance_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("maintenance_type_id", sa.Uuid(), nullable=False),
        sa.Column("garage_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=20), server_default="maintenance", nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("mileage", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("labor_cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("parts_cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('maintenance', 'repair')", name=op.f("ck_maintenance_records_kind")
        ),
        sa.CheckConstraint("cost >= 0", name=op.f("ck_maintenance_records_cost_positive")),
        sa.CheckConstraint(
            "labor_cost >= 0", name=op.f("ck_maintenance_records_labor_cost_positive")
        ),
        sa.CheckConstraint("mileage >= 0", name=op.f("ck_maintenance_records_mileage_positive")),
        sa.CheckConstraint(
            "parts_cost >= 0", name=op.f("ck_maintenance_records_parts_cost_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_maintenance_records_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["garage_id"],
            ["garages.id"],
            name=op.f("fk_maintenance_records_garage_id_garages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["maintenance_type_id"],
            ["maintenance_types.id"],
            name=op.f("fk_maintenance_records_maintenance_type_id_maintenance_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_maintenance_records_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_records")),
    )
    op.create_index(
        op.f("ix_maintenance_records_garage_id"), "maintenance_records", ["garage_id"], unique=False
    )
    op.create_index(
        op.f("ix_maintenance_records_maintenance_type_id"),
        "maintenance_records",
        ["maintenance_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maintenance_records_vehicle_id_service_date"),
        "maintenance_records",
        ["vehicle_id", "service_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_maintenance_records_vehicle_id_service_date"), table_name="maintenance_records"
    )
    op.drop_index(
        op.f("ix_maintenance_records_maintenance_type_id"), table_name="maintenance_records"
    )
    op.drop_index(op.f("ix_maintenance_records_garage_id"), table_name="maintenance_records")
    op.drop_table("maintenance_records")
    # ### end Alembic commands ###
