"""create notes

Revision ID: cbdee638d635
Revises: 1a135edeb800
Create Date: 2026-10-07 11:19:08.824953+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "cbdee638d635"
down_revision: str | None = "1a135edeb800"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("entity_type", sa.String(length=30), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=20), server_default="general", nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('general', 'maintenance', 'repair', 'part', 'problem', 'document')",
            name=op.f("ck_notes_category"),
        ),
        sa.CheckConstraint(
            "entity_type IN ('maintenance_record', 'part_replacement', 'expense', 'vehicle_document', 'fuel_record', 'tire')",
            name=op.f("ck_notes_entity_type"),
        ),
        sa.CheckConstraint(
            "(entity_type IS NULL) = (entity_id IS NULL)",
            name=op.f("ck_notes_entity_type_and_id_together"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notes_user_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_notes_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
    )
    op.create_index(
        op.f("ix_notes_entity_type_entity_id"), "notes", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_notes_vehicle_id_created_at"), "notes", ["vehicle_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notes_vehicle_id_created_at"), table_name="notes")
    op.drop_index(op.f("ix_notes_entity_type_entity_id"), table_name="notes")
    op.drop_table("notes")
    # ### end Alembic commands ###
