"""create fuel records and link expenses

Revision ID: 4ae57620391f
Revises: a87cf4ec144e
Create Date: 2026-10-06 15:30:50.197565+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "4ae57620391f"
down_revision: str | None = "a87cf4ec144e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fuel_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("fill_date", sa.Date(), nullable=False),
        sa.Column("mileage", sa.Integer(), nullable=False),
        sa.Column("liters", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("price_per_liter", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("full_tank", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("missed_previous", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("fuel_type", sa.String(length=20), nullable=True),
        sa.Column("gas_station", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fuel_type IN ('petrol', 'diesel', 'e85', 'lpg', 'cng', 'hydrogen', 'other')",
            name=op.f("ck_fuel_records_fuel_type"),
        ),
        sa.CheckConstraint("liters > 0", name=op.f("ck_fuel_records_liters_positive")),
        sa.CheckConstraint("mileage >= 0", name=op.f("ck_fuel_records_mileage_positive")),
        sa.CheckConstraint(
            "price_per_liter >= 0", name=op.f("ck_fuel_records_price_per_liter_positive")
        ),
        sa.CheckConstraint("total_price >= 0", name=op.f("ck_fuel_records_total_price_positive")),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_fuel_records_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_fuel_records_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fuel_records")),
    )
    op.create_index(
        op.f("ix_fuel_records_vehicle_id_fill_date"),
        "fuel_records",
        ["vehicle_id", "fill_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fuel_records_vehicle_id_mileage"),
        "fuel_records",
        ["vehicle_id", "mileage"],
        unique=False,
    )
    op.add_column("expenses", sa.Column("fuel_record_id", sa.Uuid(), nullable=True))
    op.create_unique_constraint(op.f("uq_expenses_fuel_record_id"), "expenses", ["fuel_record_id"])
    op.create_foreign_key(
        op.f("fk_expenses_fuel_record_id_fuel_records"),
        "expenses",
        "fuel_records",
        ["fuel_record_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # Check constraints are not autogenerated: extend the single-source rule to fuel.
    op.drop_constraint(op.f("ck_expenses_single_source"), "expenses", type_="check")
    op.create_check_constraint(
        op.f("ck_expenses_single_source"),
        "expenses",
        "num_nonnulls(maintenance_record_id, part_replacement_id, fuel_record_id) <= 1",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_expenses_single_source"), "expenses", type_="check")
    op.create_check_constraint(
        op.f("ck_expenses_single_source"),
        "expenses",
        "num_nonnulls(maintenance_record_id, part_replacement_id) <= 1",
    )
    op.drop_constraint(
        op.f("fk_expenses_fuel_record_id_fuel_records"), "expenses", type_="foreignkey"
    )
    op.drop_constraint(op.f("uq_expenses_fuel_record_id"), "expenses", type_="unique")
    op.drop_column("expenses", "fuel_record_id")
    op.drop_index(op.f("ix_fuel_records_vehicle_id_mileage"), table_name="fuel_records")
    op.drop_index(op.f("ix_fuel_records_vehicle_id_fill_date"), table_name="fuel_records")
    op.drop_table("fuel_records")
    # ### end Alembic commands ###
