"""create part types and part replacements

Revision ID: 994981bb566d
Revises: cc5c160f6ff0
Create Date: 2026-10-06 15:11:38.381131+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "994981bb566d"
down_revision: str | None = "cc5c160f6ff0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "part_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("default_lifetime_km", sa.Integer(), nullable=True),
        sa.Column("default_lifetime_months", sa.SmallInteger(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('engine', 'filters', 'brakes', 'electrical', 'tires', 'suspension', 'transmission', 'cooling', 'lighting', 'body', 'other')",
            name=op.f("ck_part_types_category"),
        ),
        sa.CheckConstraint(
            "default_lifetime_km > 0", name=op.f("ck_part_types_default_lifetime_km_positive")
        ),
        sa.CheckConstraint(
            "default_lifetime_months > 0",
            name=op.f("ck_part_types_default_lifetime_months_positive"),
        ),
        sa.CheckConstraint(
            "user_id IS NOT NULL OR code IS NOT NULL",
            name=op.f("ck_part_types_system_type_has_code"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_part_types_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_part_types")),
    )
    op.create_index(op.f("ix_part_types_user_id"), "part_types", ["user_id"], unique=False)
    op.create_index(
        "uq_part_types_code",
        "part_types",
        ["code"],
        unique=True,
        postgresql_where=sa.text("user_id IS NULL"),
    )
    op.create_index(
        "uq_part_types_user_id_name",
        "part_types",
        ["user_id", "name"],
        unique=True,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.create_table(
        "part_replacements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("part_type_id", sa.Uuid(), nullable=False),
        sa.Column("maintenance_record_id", sa.Uuid(), nullable=True),
        sa.Column("garage_id", sa.Uuid(), nullable=True),
        sa.Column("part_name", sa.String(length=150), nullable=False),
        sa.Column("brand", sa.String(length=80), nullable=True),
        sa.Column("reference_number", sa.String(length=80), nullable=True),
        sa.Column("serial_number", sa.String(length=80), nullable=True),
        sa.Column("position", sa.String(length=30), nullable=True),
        sa.Column("quantity", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("installed_date", sa.Date(), nullable=False),
        sa.Column("installed_mileage", sa.Integer(), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("labor_cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("warranty_expiration_date", sa.Date(), nullable=True),
        sa.Column("expected_lifetime_km", sa.Integer(), nullable=True),
        sa.Column("expected_lifetime_months", sa.SmallInteger(), nullable=True),
        sa.Column("removed_date", sa.Date(), nullable=True),
        sa.Column("removed_mileage", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expected_lifetime_km > 0",
            name=op.f("ck_part_replacements_expected_lifetime_km_positive"),
        ),
        sa.CheckConstraint(
            "expected_lifetime_months > 0",
            name=op.f("ck_part_replacements_expected_lifetime_months_positive"),
        ),
        sa.CheckConstraint(
            "installed_mileage >= 0", name=op.f("ck_part_replacements_installed_mileage_positive")
        ),
        sa.CheckConstraint(
            "labor_cost >= 0", name=op.f("ck_part_replacements_labor_cost_positive")
        ),
        sa.CheckConstraint("price >= 0", name=op.f("ck_part_replacements_price_positive")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_part_replacements_quantity_positive")),
        sa.CheckConstraint(
            "removed_date IS NULL OR removed_date >= installed_date",
            name=op.f("ck_part_replacements_removed_after_installed"),
        ),
        sa.CheckConstraint(
            "removed_mileage >= 0", name=op.f("ck_part_replacements_removed_mileage_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_part_replacements_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["garage_id"],
            ["garages.id"],
            name=op.f("fk_part_replacements_garage_id_garages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["maintenance_record_id"],
            ["maintenance_records.id"],
            name=op.f("fk_part_replacements_maintenance_record_id_maintenance_records"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["part_type_id"],
            ["part_types.id"],
            name=op.f("fk_part_replacements_part_type_id_part_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_part_replacements_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_part_replacements")),
    )
    op.create_index(
        op.f("ix_part_replacements_garage_id"), "part_replacements", ["garage_id"], unique=False
    )
    op.create_index(
        "ix_part_replacements_installed",
        "part_replacements",
        ["vehicle_id", "part_type_id"],
        unique=False,
        postgresql_where=sa.text("removed_date IS NULL"),
    )
    op.create_index(
        op.f("ix_part_replacements_maintenance_record_id"),
        "part_replacements",
        ["maintenance_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_part_replacements_part_type_id"),
        "part_replacements",
        ["part_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_part_replacements_vehicle_id_installed_date"),
        "part_replacements",
        ["vehicle_id", "installed_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_part_replacements_vehicle_id_installed_date"), table_name="part_replacements"
    )
    op.drop_index(op.f("ix_part_replacements_part_type_id"), table_name="part_replacements")
    op.drop_index(
        op.f("ix_part_replacements_maintenance_record_id"), table_name="part_replacements"
    )
    op.drop_index(
        "ix_part_replacements_installed",
        table_name="part_replacements",
        postgresql_where=sa.text("removed_date IS NULL"),
    )
    op.drop_index(op.f("ix_part_replacements_garage_id"), table_name="part_replacements")
    op.drop_table("part_replacements")
    op.drop_index(
        "uq_part_types_user_id_name",
        table_name="part_types",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_part_types_code", table_name="part_types", postgresql_where=sa.text("user_id IS NULL")
    )
    op.drop_index(op.f("ix_part_types_user_id"), table_name="part_types")
    op.drop_table("part_types")
    # ### end Alembic commands ###
