"""create tires and tire events

Revision ID: 37e848934877
Revises: 7d5df43bcd7d
Create Date: 2026-10-06 15:45:40.187066+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "37e848934877"
down_revision: str | None = "7d5df43bcd7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tires",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("brand", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=True),
        sa.Column("size", sa.String(length=32), nullable=False),
        sa.Column("season", sa.String(length=20), nullable=False),
        sa.Column("dot_code", sa.String(length=20), nullable=True),
        sa.Column("position", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("condition", sa.String(length=20), nullable=True),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("installed_date", sa.Date(), nullable=True),
        sa.Column("installed_mileage", sa.Integer(), nullable=True),
        sa.Column("tread_depth_mm", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("pressure_notes", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "condition IN ('new', 'good', 'fair', 'worn', 'damaged')",
            name=op.f("ck_tires_condition"),
        ),
        sa.CheckConstraint(
            "position IN ('front_left', 'front_right', 'rear_left', 'rear_right', 'spare')",
            name=op.f("ck_tires_position"),
        ),
        sa.CheckConstraint(
            "season IN ('summer', 'winter', 'all_season')", name=op.f("ck_tires_season")
        ),
        sa.CheckConstraint(
            "status <> 'mounted' OR position IS NOT NULL",
            name=op.f("ck_tires_mounted_tire_has_position"),
        ),
        sa.CheckConstraint(
            "status IN ('mounted', 'stored', 'discarded')", name=op.f("ck_tires_status")
        ),
        sa.CheckConstraint(
            "installed_mileage >= 0", name=op.f("ck_tires_installed_mileage_positive")
        ),
        sa.CheckConstraint("price >= 0", name=op.f("ck_tires_price_positive")),
        sa.CheckConstraint("tread_depth_mm >= 0", name=op.f("ck_tires_tread_depth_positive")),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_tires_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_tires_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tires")),
    )
    op.create_index(op.f("ix_tires_vehicle_id"), "tires", ["vehicle_id"], unique=False)
    op.create_index(
        "uq_tires_mounted_position",
        "tires",
        ["vehicle_id", "position"],
        unique=True,
        postgresql_where=sa.text("status = 'mounted'"),
    )
    op.create_table(
        "tire_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tire_id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("mileage", sa.Integer(), nullable=True),
        sa.Column("from_position", sa.String(length=20), nullable=True),
        sa.Column("to_position", sa.String(length=20), nullable=True),
        sa.Column("tread_depth_mm", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('installed', 'rotated', 'removed', 'inspected', 'repaired', 'discarded')",
            name=op.f("ck_tire_events_event_type"),
        ),
        sa.CheckConstraint(
            "from_position IN ('front_left', 'front_right', 'rear_left', 'rear_right', 'spare')",
            name=op.f("ck_tire_events_from_position"),
        ),
        sa.CheckConstraint(
            "to_position IN ('front_left', 'front_right', 'rear_left', 'rear_right', 'spare')",
            name=op.f("ck_tire_events_to_position"),
        ),
        sa.CheckConstraint("mileage >= 0", name=op.f("ck_tire_events_mileage_positive")),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_tire_events_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tire_id"], ["tires.id"], name=op.f("fk_tire_events_tire_id_tires"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_tire_events_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tire_events")),
    )
    op.create_index(op.f("ix_tire_events_tire_id"), "tire_events", ["tire_id"], unique=False)
    op.create_index(
        op.f("ix_tire_events_vehicle_id_event_date"),
        "tire_events",
        ["vehicle_id", "event_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tire_events_vehicle_id_event_date"), table_name="tire_events")
    op.drop_index(op.f("ix_tire_events_tire_id"), table_name="tire_events")
    op.drop_table("tire_events")
    op.drop_index(
        "uq_tires_mounted_position",
        table_name="tires",
        postgresql_where=sa.text("status = 'mounted'"),
    )
    op.drop_index(op.f("ix_tires_vehicle_id"), table_name="tires")
    op.drop_table("tires")
    # ### end Alembic commands ###
