"""create vehicle documents

Revision ID: 43bfe75aa745
Revises: 994981bb566d
Create Date: 2026-10-06 15:13:49.904475+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "43bfe75aa745"
down_revision: str | None = "994981bb566d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicle_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("document_type", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("document_number", sa.String(length=80), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("provider", sa.String(length=120), nullable=True),
        sa.Column(
            "reminder_days",
            postgresql.ARRAY(sa.Integer()),
            server_default=sa.text("'{30,7,1,0}'"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "document_type IN ('insurance', 'registration', 'technical_inspection', 'road_tax', 'warranty', 'leasing', 'other')",
            name=op.f("ck_vehicle_documents_document_type"),
        ),
        sa.CheckConstraint(
            "expiration_date IS NULL OR issue_date IS NULL OR expiration_date >= issue_date",
            name=op.f("ck_vehicle_documents_expiration_after_issue"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_vehicle_documents_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_vehicle_documents_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle_documents")),
    )
    op.create_index(
        op.f("ix_vehicle_documents_expiration_date"),
        "vehicle_documents",
        ["expiration_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vehicle_documents_vehicle_id_expiration_date"),
        "vehicle_documents",
        ["vehicle_id", "expiration_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_vehicle_documents_vehicle_id_expiration_date"), table_name="vehicle_documents"
    )
    op.drop_index(op.f("ix_vehicle_documents_expiration_date"), table_name="vehicle_documents")
    op.drop_table("vehicle_documents")
    # ### end Alembic commands ###
