"""create expenses

Revision ID: 509870d617ee
Revises: 43bfe75aa745
Create Date: 2026-10-06 15:16:04.513557+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "509870d617ee"
down_revision: str | None = "43bfe75aa745"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("mileage", sa.Integer(), nullable=True),
        sa.Column("vendor", sa.String(length=120), nullable=True),
        sa.Column("maintenance_record_id", sa.Uuid(), nullable=True),
        sa.Column("part_replacement_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('maintenance', 'repairs', 'parts', 'fuel', 'insurance', 'taxes', 'parking', 'tolls', 'fines', 'washing', 'inspection', 'registration', 'other')",
            name=op.f("ck_expenses_category"),
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_expenses_amount_positive")),
        sa.CheckConstraint("mileage >= 0", name=op.f("ck_expenses_mileage_positive")),
        sa.CheckConstraint(
            "num_nonnulls(maintenance_record_id, part_replacement_id) <= 1",
            name=op.f("ck_expenses_single_source"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_expenses_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["maintenance_record_id"],
            ["maintenance_records.id"],
            name=op.f("fk_expenses_maintenance_record_id_maintenance_records"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["part_replacement_id"],
            ["part_replacements.id"],
            name=op.f("fk_expenses_part_replacement_id_part_replacements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_expenses_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expenses")),
        sa.UniqueConstraint(
            "maintenance_record_id", name=op.f("uq_expenses_maintenance_record_id")
        ),
        sa.UniqueConstraint("part_replacement_id", name=op.f("uq_expenses_part_replacement_id")),
    )
    op.create_index(
        op.f("ix_expenses_vehicle_id_category"),
        "expenses",
        ["vehicle_id", "category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_expenses_vehicle_id_expense_date"),
        "expenses",
        ["vehicle_id", "expense_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expenses_vehicle_id_expense_date"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_vehicle_id_category"), table_name="expenses")
    op.drop_table("expenses")
    # ### end Alembic commands ###
