"""create attachments and vehicle image

Revision ID: 1a135edeb800
Revises: 37e848934877
Create Date: 2026-10-06 15:49:50.398538+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "1a135edeb800"
down_revision: str | None = "37e848934877"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("storage_backend", sa.String(length=20), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("checksum_sha256", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entity_type IN ('vehicle', 'maintenance_record', 'part_replacement', 'expense', 'vehicle_document', 'fuel_record', 'tire')",
            name=op.f("ck_attachments_entity_type"),
        ),
        sa.CheckConstraint("file_size > 0", name=op.f("ck_attachments_file_size_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_attachments_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_attachments_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_attachments_storage_key")),
    )
    op.create_index(
        op.f("ix_attachments_entity_type_entity_id"),
        "attachments",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(op.f("ix_attachments_vehicle_id"), "attachments", ["vehicle_id"], unique=False)
    op.add_column("vehicles", sa.Column("image_attachment_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_vehicles_image_attachment_id_attachments"),
        "vehicles",
        "attachments",
        ["image_attachment_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_vehicles_image_attachment_id_attachments"), "vehicles", type_="foreignkey"
    )
    op.drop_column("vehicles", "image_attachment_id")
    op.drop_index(op.f("ix_attachments_vehicle_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_entity_type_entity_id"), table_name="attachments")
    op.drop_table("attachments")
    # ### end Alembic commands ###
