"""create mileage history

Revision ID: d6ed9981ae86
Revises: 3cd0f848c45f
Create Date: 2026-10-06 14:56:09.167648+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "d6ed9981ae86"
down_revision: str | None = "3cd0f848c45f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mileage_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("mileage", sa.Integer(), nullable=False),
        sa.Column("recorded_on", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('initial', 'manual', 'maintenance', 'fuel', 'part', 'tire', 'obd', 'import')",
            name=op.f("ck_mileage_history_source"),
        ),
        sa.CheckConstraint("mileage >= 0", name=op.f("ck_mileage_history_mileage_positive")),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_mileage_history_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_mileage_history_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mileage_history")),
    )
    op.create_index(
        op.f("ix_mileage_history_vehicle_id_recorded_on"),
        "mileage_history",
        ["vehicle_id", "recorded_on"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mileage_history_vehicle_id_recorded_on"), table_name="mileage_history")
    op.drop_table("mileage_history")
    # ### end Alembic commands ###
