"""create maintenance types

Revision ID: fa5060fec212
Revises: fcd98ffa9cce
Create Date: 2026-10-06 15:00:14.494214+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "fa5060fec212"
down_revision: str | None = "fcd98ffa9cce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maintenance_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("default_interval_km", sa.Integer(), nullable=True),
        sa.Column("default_interval_months", sa.SmallInteger(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('engine', 'filters', 'fluids', 'brakes', 'electrical', 'tires', 'suspension', 'transmission', 'climate', 'inspection', 'body', 'repair', 'other')",
            name=op.f("ck_maintenance_types_category"),
        ),
        sa.CheckConstraint(
            "default_interval_km > 0",
            name=op.f("ck_maintenance_types_default_interval_km_positive"),
        ),
        sa.CheckConstraint(
            "default_interval_months > 0",
            name=op.f("ck_maintenance_types_default_interval_months_positive"),
        ),
        sa.CheckConstraint(
            "user_id IS NOT NULL OR code IS NOT NULL",
            name=op.f("ck_maintenance_types_system_type_has_code"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_maintenance_types_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_types")),
    )
    op.create_index(
        op.f("ix_maintenance_types_user_id"), "maintenance_types", ["user_id"], unique=False
    )
    op.create_index(
        "uq_maintenance_types_code",
        "maintenance_types",
        ["code"],
        unique=True,
        postgresql_where=sa.text("user_id IS NULL"),
    )
    op.create_index(
        "uq_maintenance_types_user_id_name",
        "maintenance_types",
        ["user_id", "name"],
        unique=True,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_maintenance_types_user_id_name",
        table_name="maintenance_types",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_maintenance_types_code",
        table_name="maintenance_types",
        postgresql_where=sa.text("user_id IS NULL"),
    )
    op.drop_index(op.f("ix_maintenance_types_user_id"), table_name="maintenance_types")
    op.drop_table("maintenance_types")
    # ### end Alembic commands ###
