"""Time-ordered UUIDv7 identifiers (RFC 9562).

UUIDv7 keeps B-tree indexes compact (new keys are appended, not scattered) and can be
generated by offline clients without coordination.
"""

import os
import time
import uuid

_RAND_A_BITS = 12
_RAND_B_BITS = 62


def uuid7() -> uuid.UUID:
    timestamp_ms = time.time_ns() // 1_000_000
    random_bits = int.from_bytes(os.urandom(10), "big")
    rand_a = (random_bits >> _RAND_B_BITS) & ((1 << _RAND_A_BITS) - 1)
    rand_b = random_bits & ((1 << _RAND_B_BITS) - 1)

    value = (timestamp_ms & ((1 << 48) - 1)) << 80
    value |= 0x7 << 76  # version
    value |= rand_a << 64
    value |= 0b10 << 62  # RFC 4122 variant
    value |= rand_b
    return uuid.UUID(int=value)
